### ISSUE TITLE
Missing thirdpartylibs.xml file

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#1]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is also a blocker for approval in the plugins db.

**Comment by Kavimukil** [comment]
@danmarsden Included Third party libs used in the plugin. Also SimpleJwt pulled other dependant libraries as well. Do We have to include that as well ?

**Comment by danmarsden** [comment]
Just a typo here:
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/main/thirdpartylibs.xml#L6
"BSB" -> "BSD"
