### ISSUE TITLE
Use Moodle's curl class instead of curl_init()

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#10]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

**Comment by Kavimukil** [comment]
@danmarsden Agreed. Now we are using moodle's curl wrapper itself for all external api calls. thanks for pointing it out
