### ISSUE TITLE
ajax.php appears to only be used for connection testing so should implement better capability checks.

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#12]
I can't see any reason for ajax.php to only have a require_login() check - I think it's only used for a connection test on the settings.php page, in which case it should really have a matching require_capability('moodle/site:config') style call.

Otherwise - any logged in user, can post "anything" to the drillbit API and get a response potentially including information they should not be able to access.

**Comment by Kavimukil** [comment]
@danmarsden Noted. Now its modified and it uses is_siteadmin() to determine if the logged in user is admin and then only it will call the test connection API. Let me know if this is fine

**Comment by danmarsden** [comment]
yeah that looks a lot safer - feel free to close this one!
