### ISSUE TITLE
class names incorrect

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#13]
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/classes/drillbit_view.class.php#L24

Ideally this should be namespaced eg:
namespace plagiarism_drillbit\form;
class view() {

Otherwise it needs to use the frankenstyle prefix eg:
class plagiarism_drillbit_view() {

Please check all your class names/functions and make sure they comply with Moodle's guidelines.

**Comment by Kavimukil** [comment]
@danmarsden Yes. Now We are following frankenstyle prefix for all class names.
