### ISSUE TITLE
This looks weird:

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#14]
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/classes/drillbit_view.class.php#L17

Do you really need the Turnitin LTI thing in there?

**Comment by Kavimukil** [comment]
No. Absolutely not. This came when copy pasting moodle license comment block from another plugin
