### ISSUE TITLE
Do module settings actually save/work?

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#15]
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/lib.php#L354

I see the corresponding "save" action hasn't been implemented for those form elements so I can't see how this would work?
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/lib.php#L373

**Comment by Kavimukil** [comment]
@danmarsden Yes. Now its implemented to work upon submission
