### ISSUE TITLE
copyright/author headers incorrect

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#17]
I'm pretty sure John McGettrick didn't write any of this code... please check all the @author and @copyright statements in your phpdoc headers to make sure they are correct.

**Comment by danmarsden** [comment]
It would be good for you to review the author/copyright errors that are showing in your phpdocs too as per the report available in the plugins db:
https://moodle.org/plugins/plagiarism_drillbit/3.5/23962?smurf=html#phpcs

Note - the copyright/author issues are blockers for approval, but the other errors in there are not blockers for approval.

**Comment by Kavimukil** [comment]
Hi Dan, 

Noted. Comments are copy pasted from other plugin resources. That's why in few files its still there. Its removed now
