### ISSUE TITLE
new global defined $pptaskcall

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#18]
Globals in Moodle must be in upper case, but ideally your code shouldn't be defining new globals if possible, and it doesn't look like this is used so probably best to remove it:
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/classes/task/update_reports.php#L40

**Comment by Kavimukil** [comment]
@danmarsden Noted. And removed.
