### ISSUE TITLE
running cron tasks every minute is bad practice.

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#20]
It is generally considered bad-practice to be running cron tasks "every minute" - most plagiairsm plugins find that running tasks every 5 minutes is sufficient.
Please look at changing the default to no less than 5 minutes - if a server admin wants to run it more frequently they can udpate it themselves within the Moodle UI.
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/main/db/tasks.php#L32

https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/main/db/tasks.php#L41

**Comment by Kavimukil** [comment]
@danmarsden Noted. Will make changes as per your suggestion
