### ISSUE TITLE
typos in lang strings

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#27]
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/main/lang/en/plagiarism_drillbit.php
"donnection" -> "connection"
"Successfull" -> "Successful"

Also - Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "View Drillbit Report";
should be:
$string['mystring'] = "View Drillbit report";

Note: this is not a blocker for approval in the plugins db.

**Comment by Kavimukil** [comment]
@danmarsden Its changed as per your suggestion
