### ISSUE TITLE
Plugins db entry states that Forum and workshop are supported which doesn't appear to be the case.

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#4]
The plugins db entry states that you support the forum and workshop activity but looking through your code it appears that this is not implemented completely yet? - Can you please confirm that this works?

If forum/workshop support is not yet implemented we can still approve this, but you need to:"
1) update your plugins db entry to make it clear that it only currently supports the assignment activity.
2) Remove/hide the settings on the config page that allow the admin to "enable" support for workshop/forum - these should not be displayed until your plugin actually supports these activity types.

**Comment by Kavimukil** [comment]
@danmarsden In future, We will support workshop and forum. As now now at code level we have handled to make it available only for Assignments. Let me know if that's alight

**Comment by danmarsden** [comment]
You still have the text "It can be integrated with existing Moodle Assignment, forum, and workshop modules." In the plugins db entry which is incorrect.

**Comment by Kavimukil** [comment]
@danmarsden Will change it there as well when submitting it again

**Comment by danmarsden** [comment]
I see you submitted it again for us to review, but your plugins db description still states that your plugin supports workshop/forum when it does not.

**Comment by Kavimukil** [comment]
@danmarsden  It is corrected in Moodle plugins db.

**Comment by danmarsden** [comment]
That looks a bit better thanks. - feel free to close this off!
