### ISSUE TITLE
incorrect copyright headers

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#7]
You may have copied some code from the Turnitin plugin - but iParadigms did not write this code - you should have your company name listed there:
eg:
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/lang/en/plagiarism_drillbit.php#L19

I would suggest you look through your full codebase for "turnitin" as well - I see a few references in there that should probably not be there.

**Comment by Kavimukil** [comment]
Yes. Comments copied form another plugin. Changed it overall in all files
