### ISSUE TITLE
hard-coded english language strings

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#8]
eg:
https://github.com/drillbit-dev/moodle-plagiarism_drillbit/blob/16d6ed045bb06f8270c62d9a78b51e020ebdd702/settings.php#L41

Please check your code and make sure all user-facing strings are pulled from the lang string file.

**Comment by Kavimukil** [comment]
As suggested, Made changes accordingly
