### ISSUE TITLE
Functions should be prefixed with frankenstlye name or namespaced inside classes

### ISSUE THREAD

**Issue by danmarsden** [drillbit-dev/moodle-plagiarism_drillbit#9]
functions like get_file_headers(), update_expired_jwt_token(), get_login_token(), CallExternalAPI() are incorrectly named and could clash with internal Moodle functions.

All functions should use our frankenstyle rules:
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions
https://docs.moodle.org/dev/Frankenstyle#Function_names

**Comment by Kavimukil** [comment]
@danmarsden We are following frankenstyle names for all functions.
